{% set version = "2.0.1" %}

package:
  name: openalea.grapheditor
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - openalea.deploy
  run:
    - openalea.deploy
    - openalea.core
    - openalea.vpltk

test:
  imports:
    - openalea.grapheditor

about:
  home: http://github.com/openalea/visualea
  license: Cecill-c License
  summary: GraphEditor package for OpenAlea.

