{% set version = "2.0.1" %}

package:
  name: openalea.visualea
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - openalea.deploy
  run:
    - openalea.deploy
    - openalea.core
    - openalea.vpltk
    - openalea.grapheditor
    - qt <5
    - pyqt
    - ipython-qtconsole
    - ipython

test:
  imports:
    - openalea.visualea

about:
  home: http://github.com/openalea/visualea
  license: Cecill-c License
  summary: OpenAlea visual programming environment.

