{% set version = "2.0.0" %}

package:
  name: openalea.core
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - openalea.deploy #==2.0.0
  run:
    - python
    - openalea.vpltk

test:
  imports:
    - openalea.core

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License
  summary: OpenAlea Core component platform.

