{% set version = "2.0.1" %}

package:
  name: openalea.core
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 1
  script: python setup.py install --prefix=$PREFIX

requirements:
  build:
    - openalea.deploy #==2.0.0
  run:
    - python
    - ipykernel

test:
  imports:
    - openalea.core
test:
  requires:
    - nose
  imports:
    - openalea.core
  source_files:
    - test/
    - share/
  commands:
    - nosetests -v

about:
  home: http://github.com/openalea/core
  license: Cecill-c License
  summary: OpenAlea Core component and Scientific Workflow platform.

